правки ко второму спринту
kukabuu/mf.messenger.praktikum.yandex pull request #2
Opened 2021-02-02 10:22 UTC by kukabuu

Здесь есть правки для второго и третьего спринтов. Извини, не смогла разобраться, как сделать ветку только с исправлениями для второго спринта

2021-02-04 16:06 UTC, froziq requested changes
не увидел ссылку в heroku и нужные скрипты для сборки проекта

умело обращаешься с ts, молодец)

.js и .js.map файлов не должно быть в проекте, они должны собираться и складываться в папочку с собранными файлами и не должны пушиться в git. для удобной организации файловой структуры советую разделить весь проект на папки `src` и `static` , потому что обычно удобно файлы делить по трём папкам: static, src, build.

– В папке static лежат только статичные файлы, то есть картинки, иконки, шрифты, html – те файлы, которые в процессе сборки никакой обработки не проходят.
– В папке src лежат исходники scss и ts. Обычно здесь больше ничего и не располагают. В редких случаях в эту папку кладут svg иконки.
– В папку build собирается весь проект, то есть после компиляции ts файлы попадают в build. После обработки scss тоже попадают в build. Затем обычным самописным скриптом копируются все нужные файлы из static в build.

В итоге получается полностью собранная папка build, готовая к разворачиванию на каком-то хостинге или для раздачи из сервера. Сама build папка не попадает в git (добавляет в .gitignore), она каждый раз заново собирается на том устройстве, которое будет раздавать её.

2021-02-04 16:06 UTC, froziq commented on README.md
> +В проекте используются модули ES6.
как детально всё описано) здорово

2021-02-04 16:06 UTC, froziq commented on package.json
> +    "tsc-watcher": "tsc -w"
а других скриптов для сборки приложения нет ? ведь кроме запуска для разработки приложение нужно собирать, например, для выгрузки в netlify, это задание сейчас в 1 спринте, и оно должно быть выполнено

2021-02-04 16:06 UTC, froziq commented on src/api/profileAPI.ts
> +	create() {
странное именование метода, который делает logout. в коде будет вызов вида `ProfileAPI.create()` , который на самом деле делает logout, максимально не очевидно, хорошо бы называть методы соответствующе. а вообще не вижу смысла в этой дополнительной абстракции, которая вокруг `profileAPIInstance`. ведь есть же все эти методы описанные, зачем ещё класс ProfileAPI ?

2021-02-04 16:06 UTC, froziq commented on src/api/profileAPI.ts
> +		console.log('logout clicked')
отладочную информацию стоит удалять

2021-02-04 16:06 UTC, froziq commented on src/api/profileChangeInfoAPI.ts
> +				'Content-type': 'application/json; charset=utf-8'
предлагаю в основной функции, которая делает непосредственно запрос вынести заголовки по умолчанию, чтоб одно и то же не писать во многих файлах

2021-02-04 16:06 UTC, froziq commented on src/api/userChatAPI.ts
> +}
все эти файлы выше с именем `*API.ts` можно удалить и использовать `*APIInstance` напрямую без каких-то дополнительных абстракций. либо можно наоборот весь функционал из userChatAPIInstance вытащить сюда в UserChatAPI, в общем иметь под это дело всего один файл под каждую сущность (юзер, чат и тд)

2021-02-04 16:06 UTC, froziq commented on src/components/Input/index.ts
> +import Block from '../../core/Block/index.js';
файлы все ts а импорты через .js, для чего это сделано я понимаю. но выглядит не очень. хорошо бы убрать все расширения .js , а после сборки запускать скрипт, который будет проходиться по всем файлам и менять расширение вида `import Block from '../../core/Block/index';` на `import Block from '../../core/Block/index.js';`

такой скрипт если писать не хочется, гуглится довольно легко

2021-02-04 16:06 UTC, froziq commented on src/components/Notification/index.ts
> +		child.classList.remove(Visibility.CLOSE)
а не достаточно ли одного класса ? ведь состояние бинарное, либо "Виден элемент", либо "Не виден элемент". кажется, что можно обойтись одним `notification--opacity-0`

p.s. в конце строки не хватает символа `;`

p.p.s можно подключить eslint, чтобы не заморачиваться с формативанием, он будет подсвечивать все места, которые н по формату написаны

2021-02-04 16:06 UTC, froziq commented on src/components/Profile/index.ts
> +		method?: 'get' | 'post'
get post можно вынести в enum, наверняка где-то ещё пригодятся

2021-02-04 16:06 UTC, froziq commented on src/controllers/ProfileController/index.ts
> +				if (response.status !== 200) {
проверку статуса хорошо бы вынести тоже в функцию основную, которая запрос делает

2021-02-04 16:06 UTC, froziq commented on src/controllers/SignInController/index.ts
> +		if (SignInController.__instance) {
можно было бы создать класс singletone и от него наследовать все, где этот паттерн используется, а то приходится сейчас в каждом классе одно и то же писать

2021-02-04 16:06 UTC, froziq commented on src/core/BaseAPI/index.ts
> +export default class BaseAPI {
вот в этом классе кажется нет смысла, выше в комментах про него писал уже

2021-02-04 16:06 UTC, froziq commented on src/core/HTTP/index.ts
> +      if (headers) {
предлагаю в этом модуле в самом верху определить константу с заголовками по умолчанию, которые чаще всего встречаются в проекте

```
const defaultHeaders = {
  'Content-Type': 'application/json',
}; 
```

затем соединять заголовки по умолчанию с заголовками, которые пришли из функций и по этим объединенным заголовкам уже проходиться через forEach

```
const mergedHeaders = {
    ...defaultHeaders,
    ...headers,
};

Object.keys(mergedHeaders).forEach((key) => { 
```

таким образом мы уменьшим дублирование кода, вызовы функций апи станут намного короче

2021-02-04 16:06 UTC, froziq commented on src/core/HTTP/index.ts
> +        resolve(xhr);
здесь можно сразу проверять статус 200 или нет и в зависимости от этого либо resolve вызывать, либо reject

2021-02-04 16:06 UTC, froziq commented on src/core/Main/main.ts
> +// }, 5000);
комменты лучше удалять, они ни к чему, пояснений никаких не дают, просто как мёртвый код тут лежат

2021-02-04 16:06 UTC, froziq commented on src/core/Store/index.ts
> +				self.status = 'resting';
чем здесь является `self` ? нигде нет определения

2021-02-04 16:06 UTC, froziq commented on src/utils/togglePopup.ts
> +	console.log($popup?.classList)
два вызова console.log здесь для отладки ? их бы удалить

2021-02-09 10:50 UTC, froziq approved these changes
Привет.

Спасибо за исправления. Работа всем условиям удовлетворяет, принимаю её :)

2021-02-09 10:50 UTC, froziq commented on package.json
> +    "clean": "rm -r build",
для подобных скриптов удаления и копирования лучше использовать кроссплатформенные решения вроде rimraf (https://www.npmjs.com/package/rimraf) и shx (https://www.npmjs.com/package/shx)

иначе могут возникнуть в будущем проблемы при использовании этих скриптов на windows

2021-02-09 12:50 UTC, kukabuu commented on package.json
> +    "clean": "rm -r build",
спасибо!)

2021-02-28 19:57 UTC, closed without merging